# Pandas Lesson

How to process data using Pandas

In [2]:
import pandas as pd

In [3]:
periodic_data = pd.read_csv('PubChemElements_all.csv')

In [4]:
# See the first 5 rows
periodic_data.head()

,AtomicNumber,Symbol,Name,AtomicMass,CPKHexColor,ElectronConfiguration,Electronegativity,AtomicRadius,IonizationEnergy,ElectronAffinity,OxidationStates,StandardState,MeltingPoint,BoilingPoint,Density,GroupBlock,YearDiscovered
0,1,H,Hydrogen,1.008000,FFFFFF,1s1,2.20,120.0,13.598,0.754,"+1, -1",Gas,13.81,20.28,0.000090,Nonmetal,1766
1,2,He,Helium,4.002600,D9FFFF,1s2,NaN,140.0,24.587,NaN,0,Gas,0.95,4.22,0.000179,Noble gas,1868
2,3,Li,Lithium,7.000000,CC80FF,[He]2s1,0.98,182.0,5.392,0.618,+1,Solid,453.65,1615.00,0.534000,Alkali metal,1817
3,4,Be,Beryllium,9.012183,C2FF00,[He]2s2,1.57,153.0,9.323,NaN,+2,Solid,1560.00,2744.00,1.850000,Alkaline earth metal,1798
4,5,B,Boron,10.810000,FFB5B5,[He]2s2 2p1,2.04,192.0,8.298,0.277,+3,Solid,2348.00,4273.00,2.370000,Metalloid,1808

In [5]:
# See the last 5 rows
periodic_data.tail()

,AtomicNumber,Symbol,Name,AtomicMass,CPKHexColor,ElectronConfiguration,Electronegativity,AtomicRadius,IonizationEnergy,ElectronAffinity,OxidationStates,StandardState,MeltingPoint,BoilingPoint,Density,GroupBlock,YearDiscovered
113,114,Fl,Flerovium,289.191,NaN,[Rn]7s2 7p2 5f14 6d10 (predicted),NaN,NaN,NaN,NaN,"6, 4,2, 1, 0",Expected to be a Solid,NaN,NaN,NaN,Post-transition metal,1998
114,115,Mc,Moscovium,290.196,NaN,[Rn]7s2 7p3 5f14 6d10 (predicted),NaN,NaN,NaN,NaN,"3, 1",Expected to be a Solid,NaN,NaN,NaN,Post-transition metal,2003
115,116,Lv,Livermorium,293.205,NaN,[Rn]7s2 7p4 5f14 6d10 (predicted),NaN,NaN,NaN,NaN,"+4, +2, -2",Expected to be a Solid,NaN,NaN,NaN,Post-transition metal,2000
116,117,Ts,Tennessine,294.211,NaN,[Rn]7s2 7p5 5f14 6d10 (predicted),NaN,NaN,NaN,NaN,"+5, +3, +1, -1",Expected to be a Solid,NaN,NaN,NaN,Halogen,2010
117,118,Og,Oganesson,294.214,NaN,[Rn]7s2 7p6 5f14 6d10 (predicted),NaN,NaN,NaN,NaN,"+6, +4, +2, +1, 0, -1",Expected to be a Gas,NaN,NaN,NaN,Noble gas,2006

In [6]:
# Get statistic for columns with numbers
periodic_data.describe()

,AtomicNumber,AtomicMass,Electronegativity,AtomicRadius,IonizationEnergy,ElectronAffinity,MeltingPoint,BoilingPoint,Density
count,118.000000,118.000000,95.000000,99.000000,102.000000,57.000000,103.000000,93.000000,96.000000
mean,59.500000,146.607635,1.732316,209.464646,7.997255,1.072140,1273.740553,2536.212473,7.608001
std,34.207699,89.845304,0.635187,38.569130,3.339066,0.879163,888.853859,1588.410919,5.878692
min,1.000000,1.008000,0.700000,120.000000,3.894000,0.079000,0.950000,4.220000,0.000090
25%,30.250000,66.480000,1.290000,187.000000,6.020500,0.470000,516.040000,1180.000000,2.572500
50%,59.500000,142.573850,1.620000,209.000000,6.960000,0.754000,1191.000000,2792.000000,7.072000
75%,88.750000,226.777165,2.170000,232.000000,8.998500,1.350000,1806.500000,3618.000000,10.275250
max,118.000000,294.214000,3.980000,348.000000,24.587000,3.617000,3823.000000,5869.000000,22.570000

In [8]:
periodic_data.iloc[35:45]

,AtomicNumber,Symbol,Name,AtomicMass,CPKHexColor,ElectronConfiguration,Electronegativity,AtomicRadius,IonizationEnergy,ElectronAffinity,OxidationStates,StandardState,MeltingPoint,BoilingPoint,Density,GroupBlock,YearDiscovered
35,36,Kr,Krypton,83.80000,5CB8D1,[Ar]4s2 3d10 4p6,3.00,202.0,14.000,NaN,0,Gas,115.79,119.93,0.003733,Noble gas,1898
36,37,Rb,Rubidium,85.46800,702EB0,[Kr]5s1,0.82,303.0,4.177,0.468,+1,Solid,312.46,961.00,1.530000,Alkali metal,1861
37,38,Sr,Strontium,87.60000,00FF00,[Kr]5s2,0.95,249.0,5.695,NaN,+2,Solid,1050.00,1655.00,2.640000,Alkaline earth metal,1790
38,39,Y,Yttrium,88.90580,94FFFF,[Kr]5s2 4d1,1.22,219.0,6.217,0.307,+3,Solid,1795.00,3618.00,4.470000,Transition metal,1794
39,40,Zr,Zirconium,91.22000,94E0E0,[Kr]5s2 4d2,1.33,186.0,6.634,0.426,+4,Solid,2128.00,4682.00,6.520000,Transition metal,1789
40,41,Nb,Niobium,92.90640,73C2C9,[Kr]5s1 4d4,1.60,207.0,6.759,0.893,"+5, +3",Solid,2750.00,5017.00,8.570000,Transition metal,1801
41,42,Mo,Molybdenum,96.00000,54B5B5,[Kr]5s1 4d5,2.16,209.0,7.092,0.746,+6,Solid,2896.00,4912.00,10.200000,Transition metal,1778
42,43,Tc,Technetium,97.90721,3B9E9E,[Kr]5s2 4d5,1.90,209.0,7.280,0.550,"+7, +6, +4",Solid,2430.00,4538.00,11.000000,Transition metal,1937
43,44,Ru,Ruthenium,101.10000,248F8F,[Kr]5s1 4d7,2.20,207.0,7.361,1.050,+3,Solid,2607.00,4423.00,12.100000,Transition metal,1827
44,45,Rh,Rhodium,102.90550,0A7D8C,[Kr]5s1 4d8,2.28,195.0,7.459,1.137,+3,Solid,2237.00,3968.00,12.400000,Transition metal,1803

In [13]:
periodic_data.iloc[35:45,:4]

    AtomicNumber Symbol        Name  AtomicMass
35            36     Kr     Krypton    83.80000
36            37     Rb    Rubidium    85.46800
37            38     Sr   Strontium    87.60000
38            39      Y     Yttrium    88.90580
39            40     Zr   Zirconium    91.22000
40            41     Nb     Niobium    92.90640
41            42     Mo  Molybdenum    96.00000
42            43     Tc  Technetium    97.90721
43            44     Ru   Ruthenium   101.10000
44            45     Rh     Rhodium   102.90550

In [14]:
periodic_data.iloc[0]

AtomicNumber                     1
Symbol                           H
Name                      Hydrogen
AtomicMass                   1.008
CPKHexColor                 FFFFFF
ElectronConfiguration          1s1
Electronegativity              2.2
AtomicRadius                   120
IonizationEnergy            13.598
ElectronAffinity             0.754
OxidationStates             +1, -1
StandardState                  Gas
MeltingPoint                 13.81
BoilingPoint                 20.28
Density                  8.988e-05
GroupBlock                Nonmetal
YearDiscovered                1766
Name: 0, dtype: object

In [15]:
# Use the iloc function to 
# select row 5
# select Row 30 to the end and the first 4 column

In [18]:
periodic_data.iloc[5]

AtomicNumber                       6
Symbol                             C
Name                          Carbon
AtomicMass                    12.011
CPKHexColor                   909090
ElectronConfiguration    [He]2s2 2p2
Electronegativity               2.55
AtomicRadius                     170
IonizationEnergy               11.26
ElectronAffinity               1.263
OxidationStates           +4, +2, -4
StandardState                  Solid
MeltingPoint                    3823
BoilingPoint                    4098
Density                        2.267
GroupBlock                  Nonmetal
YearDiscovered               Ancient
Name: 5, dtype: object

In [17]:
periodic_data.iloc[30:,:4]

     AtomicNumber Symbol           Name  AtomicMass
30             31     Ga        Gallium   69.720000
31             32     Ge      Germanium   72.630000
32             33     As        Arsenic   74.921590
33             34     Se       Selenium   78.970000
34             35     Br        Bromine   79.900000
35             36     Kr        Krypton   83.800000
36             37     Rb       Rubidium   85.468000
37             38     Sr      Strontium   87.600000
38             39      Y        Yttrium   88.905800
39             40     Zr      Zirconium   91.220000
40             41     Nb        Niobium   92.906400
41             42     Mo     Molybdenum   96.000000
42             43     Tc     Technetium   97.907210
43             44     Ru      Ruthenium  101.100000
44             45     Rh        Rhodium  102.905500
45             46     Pd      Palladium  106.400000
46             47     Ag         Silver  107.868000
47             48     Cd        Cadmium  112.410000
48             49     In         Indium  114.820000
49             50     Sn            Tin  118.710000
50             51     Sb       Antimony  121.760000
51             52     Te      Tellurium  127.600000
52             53      I         Iodine  126.904500
53             54     Xe          Xenon  131.290000
54             55     Cs         Cesium  132.905452
55             56     Ba         Barium  137.330000
56             57     La      Lanthanum  138.905500
57             58     Ce         Cerium  140.120000
58             59     Pr   Praseodymium  140.907700
59             60     Nd      Neodymium  144.240000
..            ...    ...            ...         ...
88             89     Ac       Actinium  227.027750
89             90     Th        Thorium  232.038000
90             91     Pa   Protactinium  231.035900
91             92      U        Uranium  238.028900
92             93     Np      Neptunium  237.048170
93             94     Pu      Plutonium  244.064200
94             95     Am      Americium  243.061380
95             96     Cm         Curium  247.070350
96             97     Bk      Berkelium  247.070310
97             98     Cf    Californium  251.079590
98             99     Es    Einsteinium  252.083000
99            100     Fm        Fermium  257.095110
100           101     Md    Mendelevium  258.098430
101           102     No       Nobelium  259.101000
102           103     Lr     Lawrencium  262.110000
103           104     Rf  Rutherfordium  267.122000
104           105     Db        Dubnium  268.126000
105           106     Sg     Seaborgium  271.134000
106           107     Bh        Bohrium  274.144000
107           108     Hs        Hassium  277.152000
108           109     Mt     Meitnerium  278.156000
109           110     Ds   Darmstadtium  281.165000
110           111     Rg    Roentgenium  282.169000
111           112     Cn    Copernicium  285.177000
112           113     Nh       Nihonium  286.183000
113           114     Fl      Flerovium  289.191000
114           115     Mc      Moscovium  290.196000
115           116     Lv    Livermorium  293.205000
116           117     Ts     Tennessine  294.211000
117           118     Og      Oganesson  294.214000

[88 rows x 4 columns]

In [24]:
# Use loc to access information by name
periodic_data.loc[:,["Symbol","AtomicMass"]]

    Symbol  AtomicMass
0        H    1.008000
1       He    4.002600
2       Li    7.000000
3       Be    9.012183
4        B   10.810000
5        C   12.011000
6        N   14.007000
7        O   15.999000
8        F   18.998403
9       Ne   20.180000
10      Na   22.989769
11      Mg   24.305000
12      Al   26.981538
13      Si   28.085000
14       P   30.973762
15       S   32.070000
16      Cl   35.450000
17      Ar   39.900000
18       K   39.098000
19      Ca   40.080000
20      Sc   44.955910
21      Ti   47.870000
22       V   50.941000
23      Cr   51.996000
24      Mn   54.938040
25      Fe   55.840000
26      Co   58.933190
27      Ni   58.693000
28      Cu   63.550000
29      Zn   65.400000
..     ...         ...
88      Ac  227.027750
89      Th  232.038000
90      Pa  231.035900
91       U  238.028900
92      Np  237.048170
93      Pu  244.064200
94      Am  243.061380
95      Cm  247.070350
96      Bk  247.070310
97      Cf  251.079590
98      Es  252.083000
99      Fm  257.095110
100     Md  258.098430
101     No  259.101000
102     Lr  262.110000
103     Rf  267.122000
104     Db  268.126000
105     Sg  271.134000
106     Bh  274.144000
107     Hs  277.152000
108     Mt  278.156000
109     Ds  281.165000
110     Rg  282.169000
111     Cn  285.177000
112     Nh  286.183000
113     Fl  289.191000
114     Mc  290.196000
115     Lv  293.205000
116     Ts  294.211000
117     Og  294.214000

[118 rows x 2 columns]

In [ ]:
# Get column of data by name.
# periodic_data["column_name"]

In [30]:
periodic_data["BoilingPointC"] = periodic_data["BoilingPoint"] - 273.15

In [31]:
periodic_data.head()

,AtomicNumber,Symbol,Name,AtomicMass,CPKHexColor,ElectronConfiguration,Electronegativity,AtomicRadius,IonizationEnergy,ElectronAffinity,OxidationStates,StandardState,MeltingPoint,BoilingPoint,Density,GroupBlock,YearDiscovered,BoilingPointC
0,1,H,Hydrogen,1.008000,FFFFFF,1s1,2.20,120.0,13.598,0.754,"+1, -1",Gas,13.81,20.28,0.000090,Nonmetal,1766,-252.87
1,2,He,Helium,4.002600,D9FFFF,1s2,NaN,140.0,24.587,NaN,0,Gas,0.95,4.22,0.000179,Noble gas,1868,-268.93
2,3,Li,Lithium,7.000000,CC80FF,[He]2s1,0.98,182.0,5.392,0.618,+1,Solid,453.65,1615.00,0.534000,Alkali metal,1817,1341.85
3,4,Be,Beryllium,9.012183,C2FF00,[He]2s2,1.57,153.0,9.323,NaN,+2,Solid,1560.00,2744.00,1.850000,Alkaline earth metal,1798,2470.85
4,5,B,Boron,10.810000,FFB5B5,[He]2s2 2p1,2.04,192.0,8.298,0.277,+3,Solid,2348.00,4273.00,2.370000,Metalloid,1808,3999.85

In [33]:
periodic_data.to_csv('periodic_table_new.csv')